# Generated by Django 2.0.2 on 2018-03-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_genero', models.CharField(max_length=1)),
                ('nombre_genero', models.CharField(max_length=50)),
            ],
        ),
    ]
