# Generated by Django 2.0.2 on 2018-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polcancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartimentoBiologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CompartimentoEdad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('edad_inicio', models.IntegerField(default=0)),
                ('edad_fin', models.IntegerField(default=0)),
                ('paso', models.IntegerField(default=0)),
            ],
        ),
    ]
