# Generated by Django 2.0.2 on 2018-03-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polcancer', '0003_mortalidadcbiologico_tasamortalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParejasSexuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_parejas', models.DecimalField(decimal_places=6, max_digits=9)),
                ('compartimento_edad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.CompartimentoEdad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='TasasDeFertilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasas_fertilidad', models.TextField(null=True)),
                ('compartimento_biologico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.CompartimentoBiologico')),
                ('compartimento_edad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.CompartimentoEdad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.Genero')),
            ],
        ),
    ]
