# Generated by Django 2.0.2 on 2018-03-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polcancer', '0004_parejassexuales_tasasdefertilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobertura', models.DecimalField(decimal_places=6, max_digits=15)),
                ('compartimento_edad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.CompartimentoEdad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_poblacion', models.BigIntegerField(default=0)),
                ('compartimentos_biologicos', models.TextField()),
                ('compartimentos_edad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProbabilidadesBiologicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.DecimalField(decimal_places=6, max_digits=9)),
                ('compartimento_biologico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.CompartimentoBiologico')),
                ('compartimento_edad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.CompartimentoEdad')),
            ],
        ),
        migrations.CreateModel(
            name='Tamizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba_primaria', models.TextField(null=True)),
                ('prueba_followup', models.TextField(null=True)),
                ('periodo_inicio', models.IntegerField(default=0)),
                ('periodo_fin', models.IntegerField(default=0)),
                ('adherencia', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobertura', models.BigIntegerField(default=0)),
                ('periodo_inicio', models.IntegerField(default=0)),
                ('periodo_fin', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='politica',
            name='esquema_tamizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.Tamizaje'),
        ),
        migrations.AddField(
            model_name='politica',
            name='esquema_vacunacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.Vacunacion'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='politica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polcancer.Politica'),
        ),
    ]
